import type { Metadata } from "next";
import { Fira_Sans } from 'next/font/google';
import "./globals.css";

const sans = Fira_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
  preload: true,
  adjustFontFallback: true,
  weight: "400",
});

export const metadata: Metadata = {
  title: "Netflix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
